stages:
  get_data:
    cmd: python3 src/stage_01_get_data.py --config=config.yaml
    deps:
      - src/stage_01_get_data.py
      - utils.py
      - config.yaml
    outs:
      - artifacts/data/stack_overflow_queries.xml

  prepare_data:
    cmd: python3 src/stage_02_prepare.py --config=config.yaml --params=params.yaml
    deps:
      - src/stage_02_prepare.py
      - utils.py
      - config.yaml
    params: 
      - train_test.seed
      - train_test.split
    outs:
      - artifacts/prepared/train.tsv
      - artifacts/prepared/test.tsv

  featurization:
    cmd: python3 src/stage_03_featurization.py --config=config.yaml --params=params.yaml
    deps: 
      - src/stage_01_get_data.py
      - src/stage_02_prepare.py
      - config.yaml
    params:
      - featurize.max_featurize
      - featurize.ngrams
    outs:
      - artifacts/features/train.pkl
      - artifacts/features/test.pkl


  train:
    cmd: python src/stage_04_train.py --config=config.yaml --params=params.yaml
    deps:
      - src/stage_04_train.py
      - utils.py
      - artifacts/features/train.pkl
      - config.yaml
    params:
      - train.seed
      - train.n_est  
      - train.min_split  
    outs:
      - artifacts/model/model.pkl

  stage_05_evaluate:
    cmd: python src/stage_05_model_evaluate.py --config=config.yaml
    deps:
      - src/stage_05_model_evaluate.py
      - utils.py
      - artifacts/features/test.pkl
      - config.yaml
      - artifacts/model/model.pkl
    metrics:
      - scores.json:
          cache: false
    plots:
     - prc.json:
        cache: false
        x: recall
        y: precision
     - roc.json:
        cache: false
        x: fpr
        y: tpr