name: StackOverflowQueryPrediction

on: [push]

jobs:
  deploy-runner:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
      - name: 'Deploy runner in ec2'
        shell: bash
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cml runner launch \
          --cloud=aws \
          --cloud-region=ap-south-1 \
          --cloud-type=t2.medium \
          --labels=cml-runner
  train-and-report:
    runs-on: [self-hosted, cml-runner]
    needs: deploy-runner
    timeout-minutes: 50400 # 35 days
    container: docker://iterativeai/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - name: Train and Report
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          dvc repro         
          echo "# REPORTS" >> report.md
          echo "## metrics" >> report.md
          cat scores.json >> report.md
          dvc metrics show >> report.md
          cml-send-comment report.md